;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Encounter.Category.Prototype",DevComment="Encounter.Category.Prototype")
+GameplayTagList=(Tag="Encounter.Requirement.SlowPlayer",DevComment="Encounter.Requirement.SlowPlayer")
+GameplayTagList=(Tag="Encounter.Style.Ambient",DevComment="Ambient world event.")
+GameplayTagList=(Tag="Encounter.Type.Calm",DevComment="Calm, non-threatening encounter.")
+GameplayTagList=(Tag="Encounter.Type.Suspicious",DevComment="Suspicious or tense encounter.")
+GameplayTagList=(Tag="Point.Showroom",DevComment="Point.Showroom")
+GameplayTagList=(Tag="Region.Showroom",DevComment="Player is inside the showroom region.")

